services:
  - name: BroadcastMvcApp
    type: web
    env: dotnet
    plan: free
    buildCommand: "dotnet publish -c Release -o out"
    startCommand: "dotnet out/BroadcastMvcApp.dll"
    repo: https://github.com/douglasaubre51/BroadcastMvcApp

    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production

    healthCheckPath: /
    autoDeploy: true
