services:
  - name: my-dotnet-mvc-app
    type: web
    env: dotnet
    plan: free
    buildCommand: dotnet publish -c Release -o out
    startCommand: dotnet out/my-dotnet-mvc-app.dll
    repo: https://github.com/your-repo/my-dotnet-mvc-app

    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production

    healthCheckPath: /
    autoDeploy: true
