using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace BroadcastMvcApp.Migrations
{
    /// <inheritdoc />
    public partial class removednotmappedattributesanddatabaseautogeneratedidentity : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Accounts_Channels_ChannelId",
                table: "Accounts");

            migrationBuilder.DropIndex(
                name: "IX_Accounts_ChannelId",
                table: "Accounts");

            migrationBuilder.DropColumn(
                name: "ChannelId",
                table: "Accounts");

            migrationBuilder.CreateTable(
                name: "AccountChannel",
                columns: table => new
                {
                    AccountsAccountId = table.Column<int>(type: "int", nullable: false),
                    channelsChannelId = table.Column<int>(type: "int", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AccountChannel", x => new { x.AccountsAccountId, x.channelsChannelId });
                    table.ForeignKey(
                        name: "FK_AccountChannel_Accounts_AccountsAccountId",
                        column: x => x.AccountsAccountId,
                        principalTable: "Accounts",
                        principalColumn: "AccountId",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_AccountChannel_Channels_channelsChannelId",
                        column: x => x.channelsChannelId,
                        principalTable: "Channels",
                        principalColumn: "ChannelId",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_AccountChannel_channelsChannelId",
                table: "AccountChannel",
                column: "channelsChannelId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "AccountChannel");

            migrationBuilder.AddColumn<int>(
                name: "ChannelId",
                table: "Accounts",
                type: "int",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_Accounts_ChannelId",
                table: "Accounts",
                column: "ChannelId");

            migrationBuilder.AddForeignKey(
                name: "FK_Accounts_Channels_ChannelId",
                table: "Accounts",
                column: "ChannelId",
                principalTable: "Channels",
                principalColumn: "ChannelId");
        }
    }
}
